# services:
#   # api:
#   #   build: .
#   #   container_name: swiftmeals-api
#   #   ports:
#   #     - 5000:5000
#   #   command: "npm start"

#   rolamax-mongodb:
#     container_name: swiftmeals-mongodb
#     image: mongo
#     restart: always
#     command: "mongod --port 27017"
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: rolamenttrade
#       MONGO_INITDB_ROOT_PASSWORD: Rotimi051280
#     volumes:
#       - ./data:/data/db

#   medLink-mongo-express:
#     container_name: swiftmeals-mongo-express
#     image: mongo-express
#     restart: always
#     ports:
#       - 8080:8080
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: rolamenttrade
#       ME_CONFIG_MONGODB_ADMINPASSWORD: Rotimi051280
#       ME_CONFIG_MONGODB_URL: 
#       ME_CONFIG_BASICAUTH: false


version: "3.8"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
